export const GENERATE_RANDOM_QUOTE = "GENERATE_RANDOM_QUOTE";
export const GENERATE_SUCCESS = "GENERATE_SUCCESS";
export const GENERATE_REQUEST = "GENERATE_REQUEST";
export const GENERATE_ERROR = "GENERATE_ERROR";